on:
  push:
    branches: main

name: Render & Deploy Site

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master

      - uses: r-lib/actions/setup-pandoc@master

      - name: Install dependencies
        run: |
          install.packages("rmarkdown")
          install.packages("distill")
          install.packages("postcards")
          install.packages("devtools")
          install.packages("fs")
        shell: Rscript {0}

      - name: Render Site
        run: Rscript -e 'rmarkdown::render_site("distill", encoding = "UTF-8")'

      - name: Commit results
        run: |
          mv distill/_site/ ../tmp
          git fetch
          git checkout rendered-website
          rm -r *
          cp -r ../tmp/* .
          git add -A
          git commit -m 'Render' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
